const PATH_TO_NETWORKS = "./synthetic_networks"
const PATH_TO_PLOTS = "./plots"
const OPINION_RANGE = 0:2π
const OPINION_VALUE = [-1, 1]
const GLOBAL_INFLUENCE = 1.0
const TRUST_LEVEL = 0.5
const NUM_STEPS = 10000
const GLOBAL_PERIOD = 50
const λ = 0.5